---
  version: '3.5'

  networks:
    water_auth:

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key
    oauth_ssl_crt:
      file: ./certificates/oauth2/oauth2-wildcard-dev.crt
    oauth_ssl_key:
      file: ./certificates/oauth2/oauth2-wildcard-dev.key
    saml_ssl_crt:
      file: ./certificates/saml/saml-wildcard-dev.crt
    saml_ssl_key:
      file: ./certificates/saml/saml-wildcard-dev.key

  services:
    database:
      image: mysql:8
      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
      networks:
        water_auth:
          aliases:
            - container.database.docker
      environment:
        - MYSQL_ROOT_PASSWORD=changeMe
        - MYSQL_USER=mysqluser
        - MYSQL_PASSWORD=mysqluser
        - MYSQL_DATABASE=waterauth

    server:
      build: .
      image: water-auth-server
      ports:
        - "443:443"
      networks:
        water_auth:
          aliases:
            - water_auth_server
      secrets:
        - source: tomcat_ssl_crt
          target: /tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /tomcat-wildcard-ssl.key
        - source: oauth_ssl_crt
          target: /oauth-wildcard-ssl.crt
        - source: oauth_ssl_key
          target: /oauth-wildcard-ssl.key
        - source: saml_ssl_crt
          target: /saml-wildcard-ssl.crt
        - source: saml_ssl_key
          target: /saml-wildcard-ssl.key
      env_file:
        - docker-compose-circlesso.env
