---
  version: '3.5'

  networks:
    water_auth:

  secrets:
    tomcat_ssl_crt:
      file: ./certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./certificates/tomcat/tomcat-wildcard-dev.key
    oauth_ssl_crt:
      file: ./certificates/oauth2/oauth2-wildcard-dev.crt
    oauth_ssl_key:
      file: ./certificates/oauth2/oauth2-wildcard-dev.key

  services:
    database:
      image: mysql:8
      networks:
        water_auth:
          aliases:
            - container.database.docker
      environment:
        - MYSQL_ROOT_PASSWORD=changeMe
        - MYSQL_USER=mysqluser
        - MYSQL_PASSWORD=mysqluser

    server:
      build: .
      image: water-auth-server
      ports:
        - "8443:8443"
      networks:
        water_auth:
          aliases:
            - water_auth_server
      command: --spring.profiles.active=localDev --spring.profiles.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration --spring.profiles.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      secrets:
        - source: tomcat_ssl_crt
          target: /tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /tomcat-wildcard-ssl.key
        - source: oauth_ssl_crt
          target: /oauth-wildcard-ssl.crt
        - source: oauth_ssl_key
          target: /oauth-wildcard-ssl.key
      env_file:
        - docker-compose-local-dev.env
